---

  - hosts: all
    sudo: True
    gather_facts: True
    tasks:
       - group_by: key=os_{{ ansible_distribution }}

  - hosts: os_Debian
    sudo: True
    gather_facts: True
    roles:
     - common
     - { role: nginx, nginx: { vhosts: [{path: 'roles/dokuwiki/templates/dokuwiki.j2', name: 'dokuwiki.local'}]}}
     - php5-fpm
     - { role: dokuwiki, dokuwiki: { farms: ['dokuwiki.local'] }}
