---
  - include: dokuwiki_os_debian7.yml tags=dokuwiki
    when: ansible_distribution == "Debian" and ansible_distribution_version|int == 7

  - include: dokuwiki_os_ubuntu.yml tags=dokuwiki
    when: ansible_distribution == "Ubuntu"
